roboflow:
  workspace: yoloseg-oxj7u
  project: yolo-seg-okjbk
  version: 6
  format: yolov11
  save_path: datasets
  overwrite: true

training:
  model_name: yolo11m-seg
  epochs: 300
  batch_size: 16
  img_size: 640
  device: '0'
  
  optimizer: AdamW
  lr0: 0.01
  lrf: 0.01
  momentum: 0.937
  weight_decay: 0.0005
  
  warmup_epochs: 3.0
  warmup_momentum: 0.8
  
  box_gain: 7.5
  cls_gain: 0.5
  dfl_gain: 1.5
  
  patience: 50
  workers: 12
  cache: 'disk'
  
  project_dir: models
  pretrain_dir: models/pretrain
  
  
  amp: true
  deterministic: true
  plots: true
  verbose: true
  seed: 42

prediction:
  predict_dir: models/production
  output_dir: output
  confidence: 0.5
  iou: 0.8
